# Currently only handles on docker host

# Input variables
#   - docker_hosts (CSV, docker host ips)
#   - docker_host_ssh_user
#   - docker_host_ssh_private_key_file

---

- hosts: localhost

  tasks:

    - add_host:
        name: "{{ item }}"
        groups: kafka_hosts
        ansible_user: "{{ remote_host_ssh_user | default('ubuntu') }}"
        ansible_ssh_private_key_file: "{{ remote_host_ssh_private_key_file }}"
      with_items:
        "{{ remote_hosts.split(',') }}"


- hosts: kafka_hosts

  tasks:
    - include_role:
        name: install_docker

    - include_role:
        name: install_docker_compose

    - include_role:
        name: install_pip_user

    - include_role:
        name: install_aws_cli

    - include_role:
        name: install_kafka_tools

    - include_role:
        name: install_java

    - include_role:
        name: ansible-role-ntp
      become: yes
