# Currently only handles on docker host

# Input variables
#   - docker_hosts (CSV, docker host ips)
#   - docker_host_ssh_user
#   - docker_host_ssh_private_key_file

---

- hosts: localhost

  tasks:

    - add_host:
        name: "{{ item }}"
        groups: docker_hosts
        ansible_user: "{{ docker_host_ssh_user | default('ubuntu') }}"
        ansible_ssh_private_key_file: "{{ docker_host_ssh_private_key_file }}"
      with_items:
        "{{ docker_hosts.split(',') }}"


- hosts: docker_hosts

  tasks:
    - include_role:
        name: install_docker
